I'm sorry, but an uncaught exception occurred.

While running game code:
IOError: [Errno 2] No such file or directory: u'C:\\Users\\hp\\AppData\\Roaming/RenPy/sample-1660812598\\persistent.1670741485.tmp'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 665, in main
    renpy.persistent.update(True)
  File "renpy/persistent.py", line 395, in update
    save()
  File "renpy/persistent.py", line 411, in save
    renpy.loadsave.location.save_persistent(data)
  File "renpy/savelocation.py", line 496, in save_persistent
    l.save_persistent(data)
  File "renpy/savelocation.py", line 347, in save_persistent
    with open(fn_tmp, "wb") as f:
IOError: [Errno 2] No such file or directory: u'C:\\Users\\hp\\AppData\\Roaming/RenPy/sample-1660812598\\persistent.1670741485.tmp'

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Road to Success 1.0
Sun Dec 11 13:52:28 2022
